GET http://localhost:3000/post

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "h",
    "content": "Gj"
}

###

PUT https://myblogwithmongoose.herokuapp.com/post
Content-Type: application/json

{   
    "_id": "62895c566cc7336293d08e74",
    "title": "aaa",
    "content": "aaaaaaaa"
}

###

DELETE http://localhost:3000/post/6287b8e67a7ef5207ded0e98
